

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

domain = "test.ruiandrebatista.com"

nodes = [
  {:hostname => "godiva", :ip => "192.168.0.40", :box => "ubuntu/trusty64", },
    {:hostname => "buga", :ip => "192.168.0.41", :box => "ubuntu/trusty64", }]

groups = {"dbservers_mysql" => ["buga"],
    "webservers" => ["godiva"],
  "mailservers" => ["buga"]}

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|




  nodes.each do |node|
    config.vm.define node[:hostname] do |node_config|
      node_config.vm.box = node[:box]
      node_config.vm.host_name = node[:hostname] + '.' + domain
      node_config.vm.network "private_network", ip: node[:ip]

      memory = node[:ram] ? node[:ram] : 256;
#      node_config.vm.customize [
#        'modifyvm', :id,
#        '--name', node[:hostname],
#        '--memory', memory.to_s
#      ]
    node_config.vm.provision "ansible" do | ansible |
      ansible.playbook = "site.yml"
      ansible.groups = groups
    end


	end
end
end