# Install security  packages
- name: Install security packages
  apt: name={{item}} state=latest
  with_items:
    - rkhunter
    - lynis


- name: remove sudo previledges
  lineinfile: dest=/etc/sudoers regexp="^%sudo" state=absent

- name: Disable Password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: Restart ssh

- name: Disable root login
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: Restart ssh


- include: fail2ban.yml
- include: ufw.yml